version: '3.8'

services:
  auth-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: find_my_buddy
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - find-my-buddy-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find_my_buddy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - find-my-buddy-network

volumes:
  postgres_data:

networks:
  find-my-buddy-network:
    driver: bridge